#This is my main automation for most short presence lights, bathrooms, entrance etc.
#Motion: Lights goes on. Saves current brightness to a INPUT_NUMBER, in case the user wants +- brigthness.
#No Motion: Lights dims down (I call a scene at lowest brightness), then turns off.
#New motion: Restores previous brightness. REASON: The dimmed scene would be the previous brigthness if not.
#My bathroom lights goes from OFF directly to %BRIGTHNESS, which is too sudden. Instead I trigger the bathroom DIM SCENE if bathroom lights are off and motion detected in the hallway.
#In this way, since the lights are already on, they will increase brigthness with a short and comfortable 1 sec duration. This is triggered on an external automation.
#Further on, the automation has conditition for all ligth automations off, or if it's Day or Night mode, whereas Night won't trigger it.


alias: Lys - Bad - Brightness by User
description: >-
  Semi Automatisk - Lysstyrke leses av en InputHelper, og oppdaterer denne med
  evt. endret lysstyrke. 

  Dimmer ned etter tid.

  Om luftfuktighet har økt en viss prosent skal Alternativ 2 med litt lenger tid
  velges, gjelder bare om lyset trigges på ny pr nå.

  Via Alternativ 3 så vil badet få lys på 1% hvis noen passerer, så det dimmer
  opp istedet for rett på når man går inn.
trigger:
  - platform: state
    entity_id:
      - binary_sensor.bathroom2_occupancy
    id: motion_detected
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.bathroom2_occupancy
    id: no_motion
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 7
      seconds: 0
condition:
  - condition: state
    entity_id: input_boolean.global_light_autom_disable
    state: "off"
  - condition: state
    entity_id: input_select.day_mode
    state: Dag
action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_detected
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.bathrom2_roof_spot
            data:
              brightness: >-
                {{
                states('input_number.bathroom2_takspotter_prev_brightness')|int
                }}
          - delay:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
          - service: input_number.set_value
            target:
              entity_id: input_number.bathroom2_takspotter_prev_brightness
            data:
              value: >-
                {{ state_attr('light.bathrom2_roof_spot','brightness') | int(0)
                }}
      - conditions:
          - condition: trigger
            id: no_motion
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.bathroom2_takspotter_prev_brightness
            data:
              value: >-
                {{ state_attr('light.bathrom2_roof_spot','brightness') | int(0)
                }}
          - service: scene.turn_on
            target:
              entity_id: scene.dimlys_bad
            metadata: {}
          - delay:
              hours: 0
              minutes: 2
              seconds: 0
              milliseconds: 0
          - type: turn_off
            device_id: 0c238058e1852aa37ccc0637be5df374
            entity_id: light.bathrom2_roof_spot
            domain: light
    default: []
mode: restart
